# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . /app

# Expose any port if needed, e.g., 8000
# EXPOSE 8000

# Start the MCP server with a default connection string (should be overridden via Smithery config)
CMD [ "python", "postgres_server.py", "postgresql://username:password@host:port/database" ]
